"""add_cascade_deletes

Revision ID: f7b08431784c
Revises: add_google_oauth
Create Date: 2026-02-14 22:20:55.381949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b08431784c'
down_revision: Union[str, Sequence[str], None] = 'add_google_oauth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('question_logs_user_id_fkey'), 'question_logs', type_='foreignkey')
    op.drop_constraint(op.f('question_logs_question_id_fkey'), 'question_logs', type_='foreignkey')
    op.create_foreign_key(None, 'question_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_logs', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('question_tags_question_id_fkey'), 'question_tags', type_='foreignkey')
    op.drop_constraint(op.f('question_tags_tag_id_fkey'), 'question_tags', type_='foreignkey')
    op.create_foreign_key(None, 'question_tags', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questions_user_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('schedules_user_id_fkey'), 'schedules', type_='foreignkey')
    op.drop_constraint(op.f('schedules_question_id_fkey'), 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedules', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key(op.f('schedules_question_id_fkey'), 'schedules', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('schedules_user_id_fkey'), 'schedules', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_user_id_fkey'), 'questions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'question_tags', type_='foreignkey')
    op.drop_constraint(None, 'question_tags', type_='foreignkey')
    op.create_foreign_key(op.f('question_tags_tag_id_fkey'), 'question_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('question_tags_question_id_fkey'), 'question_tags', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'question_logs', type_='foreignkey')
    op.drop_constraint(None, 'question_logs', type_='foreignkey')
    op.create_foreign_key(op.f('question_logs_question_id_fkey'), 'question_logs', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('question_logs_user_id_fkey'), 'question_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
